In [26]:
import numpy as np
import matplotlib.pyplot as plt

In [27]:
ar = np.array([3,5,6,2,1,5])

In [28]:
np.convolve(ar, [1,2,3]) # (3,2,1)

array([ 3, 11, 25, 29, 23, 13, 13, 15])

In [29]:
#Covolution On the Images from load_digits

In [30]:
from sklearn.datasets import load_digits
     

In [31]:

dt = load_digits(n_class=3)

In [32]:
dt.keys()

dict_keys(['data', 'target', 'frame', 'feature_names', 'target_names', 'images', 'DESCR'])

In [33]:
dt.images[0]

array([[ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.],
       [ 0.,  0., 13., 15., 10., 15.,  5.,  0.],
       [ 0.,  3., 15.,  2.,  0., 11.,  8.,  0.],
       [ 0.,  4., 12.,  0.,  0.,  8.,  8.,  0.],
       [ 0.,  5.,  8.,  0.,  0.,  9.,  8.,  0.],
       [ 0.,  4., 11.,  0.,  1., 12.,  7.,  0.],
       [ 0.,  2., 14.,  5., 10., 12.,  0.,  0.],
       [ 0.,  0.,  6., 13., 10.,  0.,  0.,  0.]])

In [34]:

# dt.target

In [35]:
dt.images.shape

(537, 8, 8)

In [36]:
X = dt.images
Y = dt.target
     

In [37]:
X = X.reshape(537,1,8,8)

In [38]:
import torch
import torch.nn as nn
from torch.optim import Adam

In [39]:
import torch

print(type(X))
print(type(Y))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [40]:
import torch

X = torch.tensor(X, dtype=torch.float32)   
Y = torch.tensor(Y, dtype=torch.long)      

In [41]:
from torch.utils.data import TensorDataset, DataLoader

dataset = TensorDataset(X, Y)
batches = DataLoader(dataset, batch_size=32, shuffle=True)

In [42]:
X = torch.FloatTensor(X)
Y = torch.LongTensor(Y)

In [43]:
X.shape

torch.Size([537, 1, 8, 8])

In [44]:
model = nn.Sequential(
    nn.Conv2d(1, 32, kernel_size=3, stride=1, padding=1),
    nn.ReLU(),
    nn.MaxPool2d(kernel_size=2, stride=2),
    nn.Conv2d(32, 64, kernel_size=3, stride=1, padding=1),
    nn.ReLU(),
    nn.MaxPool2d(kernel_size=2, stride=2),
    nn.Flatten(),
    nn.Linear(64*2*2, 128),
    nn.ReLU(),
    nn.Linear(128, 3)
)

In [45]:
loss = nn.CrossEntropyLoss()
opt = Adam(model.parameters(), lr=0.001)

In [46]:
import torch
import torch.nn as nn

lossfn = nn.CrossEntropyLoss()   # define loss
opt = torch.optim.SGD(model.parameters(), lr=0.01)

for xb, yb in batches:
    opt.zero_grad()
    
    yp = model(xb)
    
    loss = lossfn(yp, yb)   # now it works
    
    loss.backward()
    opt.step()

In [47]:

# Prediction on new data

In [48]:
newx = X[112].reshape(1,1,8,8)

In [49]:

newx.shape

torch.Size([1, 1, 8, 8])

In [50]:

Yp = model(newx)


In [51]:

Yp

tensor([[0.6959, 1.0477, 0.9587]], grad_fn=<AddmmBackward0>)

In [52]:
sx = torch.softmax(Yp, dim=1)

In [53]:

torch.argmax(sx, dim=1)

tensor([1])

In [54]:
#Class based Model

In [55]:
class MyNet(nn.Module):
  def __init__(self):
    super().__init__()
    self.conv1 = nn.Conv2d(1, 32, kernel_size=3, stride=1, padding=1)
    self.maxm = nn.MaxPool2d(kernel_size=2, stride=2)
    self.conv2 = nn.Conv2d(32, 64, kernel_size=3, stride=1, padding=1)
    self.relu = nn.ReLU()
    self.flatten = nn.Flatten()
    self.linear1 = nn.Linear(64*2*2, 128)
    self.linear2 = nn.Linear(128, 3)

  def forward(self, x):
    x = self.conv1(x)
    x = self.relu(x)
    x = self.maxm(x)
    x = self.conv2(x)
    x = self.relu(x)
    x = self.maxm(x)
    x = self.flatten(x)
    x = self.linear1(x)
    x = self.relu(x)
    x = self.linear2(x)
    return x
     

In [67]:
class MyNet(nn.Module):
  def __init__(sf):
    super().__init__()
    sf.conv1 = nn.Conv2d(1, 32, kernel_size=3, stride=1, padding=1)
    sf.maxm = nn.MaxPool2d(kernel_size=2, stride=2)
    sf.conv2 = nn.Conv2d(32, 64, kernel_size=3, stride=1, padding=1)
    sf.relu = nn.ReLU()
    sf.flatten = nn.Flatten()
    sf.linear1 = nn.Linear(64*2*2, 128)
    sf.linear2 = nn.Linear(128, 3)

  def forward(sf, x):
    print(x.shape)
    x = sf.conv1(x)
    print(x.shape)
    x = sf.relu(x)
    print(x.shape)
    x = sf.maxm(x)
    print(x.shape)
    x = sf.conv2(x)
    print(x.shape)
    x = sf.relu(x)
    print(x.shape)
    x = sf.maxm(x)
    print(x.shape)
    x = sf.flatten(x)
    print(x.shape)
    x = sf.linear1(x)
    print(x.shape)
    x = sf.relu(x)
    print(x.shape)
    x = sf.linear2(x)
    print(x.shape)
    return x

In [68]:
mod = MyNet()

In [69]:
mod(X)

torch.Size([537, 1, 8, 8])
torch.Size([537, 32, 8, 8])
torch.Size([537, 32, 8, 8])
torch.Size([537, 32, 4, 4])
torch.Size([537, 64, 4, 4])
torch.Size([537, 64, 4, 4])
torch.Size([537, 64, 2, 2])
torch.Size([537, 256])
torch.Size([537, 128])
torch.Size([537, 128])
torch.Size([537, 3])


tensor([[ 0.0352, -0.1265,  0.6858],
        [-0.0998, -0.1625,  0.9869],
        [ 0.0629, -0.1408,  1.0700],
        ...,
        [-0.2433, -0.2956,  0.9732],
        [-0.1985, -0.4121,  0.8986],
        [-0.1486, -0.2347,  0.9170]], grad_fn=<AddmmBackward0>)

In [59]:
loss = nn.CrossEntropyLoss()
opt = Adam(mod.parameters(), lr=0.001)
     

In [60]:
c=0
for epoch in range(100):
    c=c+1
    opt.zero_grad()
    yp = mod(X)
    ls = loss(yp, Y)
    ls.backward()
    opt.step()
    if c%10==0:
      print(ls.item())

torch.Size([537, 1, 8, 8])
torch.Size([537, 32, 8, 8])
torch.Size([537, 1, 8, 8])
torch.Size([537, 32, 8, 8])
torch.Size([537, 1, 8, 8])
torch.Size([537, 32, 8, 8])
torch.Size([537, 1, 8, 8])
torch.Size([537, 32, 8, 8])
torch.Size([537, 1, 8, 8])
torch.Size([537, 32, 8, 8])
torch.Size([537, 1, 8, 8])
torch.Size([537, 32, 8, 8])
torch.Size([537, 1, 8, 8])
torch.Size([537, 32, 8, 8])
torch.Size([537, 1, 8, 8])
torch.Size([537, 32, 8, 8])
torch.Size([537, 1, 8, 8])
torch.Size([537, 32, 8, 8])
torch.Size([537, 1, 8, 8])
torch.Size([537, 32, 8, 8])
0.2085554003715515
torch.Size([537, 1, 8, 8])
torch.Size([537, 32, 8, 8])
torch.Size([537, 1, 8, 8])
torch.Size([537, 32, 8, 8])
torch.Size([537, 1, 8, 8])
torch.Size([537, 32, 8, 8])
torch.Size([537, 1, 8, 8])
torch.Size([537, 32, 8, 8])
torch.Size([537, 1, 8, 8])
torch.Size([537, 32, 8, 8])
torch.Size([537, 1, 8, 8])
torch.Size([537, 32, 8, 8])
torch.Size([537, 1, 8, 8])
torch.Size([537, 32, 8, 8])
torch.Size([537, 1, 8, 8])
torch.Size([537, 32

In [61]:
#using batch process

In [66]:
from torch.utils.data import TensorDataset, DataLoader
import torch.nn as nn

# create dataset and dataloader
dataset = TensorDataset(X, Y)
dataloader = DataLoader(dataset, batch_size=32, shuffle=True)

lossfn = nn.CrossEntropyLoss()

model.train()
c = 0

for epoch in range(100):
    c += 1
    epoch_loss = 0.0
    
    for batch_X, batch_Y in dataloader:
        opt.zero_grad()
        
        yp = model(batch_X)
        
        ls = lossfn(yp, batch_Y)
        
        ls.backward()
        opt.step()
        
        epoch_loss += ls.item()

    if c % 10 == 0:
        print(epoch_loss)

8.140538424253464
8.122158616781235
8.107620388269424
8.107141852378845
8.097656846046448
8.124686002731323
8.121184974908829
8.119951248168945
8.130316406488419
8.12126299738884
